version: "3"
networks:
  banco:
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./database:/data/db
    environment:
      MONGO_INITDB_DATABASE: react-todo
    ports:
      - 27017:27017
    networks:
      - banco
  backend:
    build: ./backend/
    volumes:
      - ./backend:/usr/backend
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - banco
    ports:
      - 3000:3000
    command: npm run dev
